//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.WSCercle {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CerclePK/", ConfigurationName="WSCercle.ServiceCercle")]
    public interface ServiceCercle {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CerclePK/ServiceCercle/calculePerimetreRequest", ReplyAction="http://CerclePK/ServiceCercle/calculePerimetreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.WSCercle.calculePerimetreResponse calculePerimetre(WebService.WSCercle.calculePerimetreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CerclePK/ServiceCercle/calculePerimetreRequest", ReplyAction="http://CerclePK/ServiceCercle/calculePerimetreResponse")]
        System.Threading.Tasks.Task<WebService.WSCercle.calculePerimetreResponse> calculePerimetreAsync(WebService.WSCercle.calculePerimetreRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CerclePK/ServiceCercle/calculeSurfaceRequest", ReplyAction="http://CerclePK/ServiceCercle/calculeSurfaceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.WSCercle.calculeSurfaceResponse calculeSurface(WebService.WSCercle.calculeSurfaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CerclePK/ServiceCercle/calculeSurfaceRequest", ReplyAction="http://CerclePK/ServiceCercle/calculeSurfaceResponse")]
        System.Threading.Tasks.Task<WebService.WSCercle.calculeSurfaceResponse> calculeSurfaceAsync(WebService.WSCercle.calculeSurfaceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CerclePK/")]
    public partial class cercle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double _rayonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double _rayon {
            get {
                return this._rayonField;
            }
            set {
                this._rayonField = value;
                this.RaisePropertyChanged("_rayon");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calculePerimetre", WrapperNamespace="http://CerclePK/", IsWrapped=true)]
    public partial class calculePerimetreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CerclePK/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebService.WSCercle.cercle arg0;
        
        public calculePerimetreRequest() {
        }
        
        public calculePerimetreRequest(WebService.WSCercle.cercle arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calculePerimetreResponse", WrapperNamespace="http://CerclePK/", IsWrapped=true)]
    public partial class calculePerimetreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CerclePK/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public calculePerimetreResponse() {
        }
        
        public calculePerimetreResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calculeSurface", WrapperNamespace="http://CerclePK/", IsWrapped=true)]
    public partial class calculeSurfaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CerclePK/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebService.WSCercle.cercle arg0;
        
        public calculeSurfaceRequest() {
        }
        
        public calculeSurfaceRequest(WebService.WSCercle.cercle arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calculeSurfaceResponse", WrapperNamespace="http://CerclePK/", IsWrapped=true)]
    public partial class calculeSurfaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CerclePK/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public calculeSurfaceResponse() {
        }
        
        public calculeSurfaceResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceCercleChannel : WebService.WSCercle.ServiceCercle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCercleClient : System.ServiceModel.ClientBase<WebService.WSCercle.ServiceCercle>, WebService.WSCercle.ServiceCercle {
        
        public ServiceCercleClient() {
        }
        
        public ServiceCercleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCercleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCercleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCercleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.WSCercle.calculePerimetreResponse WebService.WSCercle.ServiceCercle.calculePerimetre(WebService.WSCercle.calculePerimetreRequest request) {
            return base.Channel.calculePerimetre(request);
        }
        
        public double calculePerimetre(WebService.WSCercle.cercle arg0) {
            WebService.WSCercle.calculePerimetreRequest inValue = new WebService.WSCercle.calculePerimetreRequest();
            inValue.arg0 = arg0;
            WebService.WSCercle.calculePerimetreResponse retVal = ((WebService.WSCercle.ServiceCercle)(this)).calculePerimetre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.WSCercle.calculePerimetreResponse> WebService.WSCercle.ServiceCercle.calculePerimetreAsync(WebService.WSCercle.calculePerimetreRequest request) {
            return base.Channel.calculePerimetreAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.WSCercle.calculePerimetreResponse> calculePerimetreAsync(WebService.WSCercle.cercle arg0) {
            WebService.WSCercle.calculePerimetreRequest inValue = new WebService.WSCercle.calculePerimetreRequest();
            inValue.arg0 = arg0;
            return ((WebService.WSCercle.ServiceCercle)(this)).calculePerimetreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.WSCercle.calculeSurfaceResponse WebService.WSCercle.ServiceCercle.calculeSurface(WebService.WSCercle.calculeSurfaceRequest request) {
            return base.Channel.calculeSurface(request);
        }
        
        public double calculeSurface(WebService.WSCercle.cercle arg0) {
            WebService.WSCercle.calculeSurfaceRequest inValue = new WebService.WSCercle.calculeSurfaceRequest();
            inValue.arg0 = arg0;
            WebService.WSCercle.calculeSurfaceResponse retVal = ((WebService.WSCercle.ServiceCercle)(this)).calculeSurface(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.WSCercle.calculeSurfaceResponse> WebService.WSCercle.ServiceCercle.calculeSurfaceAsync(WebService.WSCercle.calculeSurfaceRequest request) {
            return base.Channel.calculeSurfaceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.WSCercle.calculeSurfaceResponse> calculeSurfaceAsync(WebService.WSCercle.cercle arg0) {
            WebService.WSCercle.calculeSurfaceRequest inValue = new WebService.WSCercle.calculeSurfaceRequest();
            inValue.arg0 = arg0;
            return ((WebService.WSCercle.ServiceCercle)(this)).calculeSurfaceAsync(inValue);
        }
    }
}
